### PR TITLE
Allow only one thread can count measurements

### PR DESCRIPTION
**Pull request by eitoball**
[Test-and-set](https://en.wikipedia.org/wiki/Test-and-set)

### CODE REVIEW

**Comment by matschaffer** [comment]
I still feel unsure of this approach (we have at least two instances, a memcached or redis would
incur more costs).

Have you considered a regularly generated (hourly cron) db entry?

**Comment by eitoball** [comment]
> I still feel unsure of this approach (we have at least two instances, a memcached or redis would
> incur more costs).

@matschaffer I realize that `Rails.cache` is memory cache and available only for one process. But, it should solve case mentioned in #741

> Have you considered a regularly generated (hourly cron) db entry?

A little, but I thought that storing one number into database is too much. How do you think about it such as table schema?

**Comment by matschaffer** [comment]
> How do you think about it such as table schema?

I was imagining something like `rails generate model CounterCache name:string:index value:integer` could do the trick.

I'm happy to give what's in this PR a try if you think it'll help. So long we can do it without additional infrastructure spend (e.g., adding a redis/memcached).

**Comment by matschaffer** [comment]
Noting that @nokton mentioned using `SELECT reltuples::bigint AS estimate FROM pg_class where relname='mytable';` for a the measurements `count(*)`

> plz don't worry about the accuracy thing - it will report lower than what it is, but that is true for whatever number we post as it is just a snapshot in time. Not sure if you're running Analyze but that maybe needed

**Comment by matschaffer** [comment]
Can probably close in favor of https://github.com/Safecast/safecastapi/pull/792, but will see how it goes in prod anyway.

**Pull request closed without merging**
