### PR TITLE
Change to fetch icon files from api.safecast.org

### PR DESCRIPTION
**Pull request by eitoball**
Related #752 

This PR should be merged after merging #754

### CODE REVIEW

**Review by matschaffer — APPROVED** [review]

**Comment by matschaffer** [comment]
I’m still interested in switching to a kmz with icons embedded.  But this seems like a good step forward in the mean time.

**Comment by eitoball** [comment]
Deployed 3fcc10d6ab8586cf718562ce35e40bda19d3e1ac to dev environment, and verified that icon files can be accessed like http://safecastapi-dev-019.baebmmfncu.us-west-2.elasticbeanstalk.com/kml/darkOrange.png

**Review by matschaffer — APPROVED** [review]
Still lgtm

**Comment by eitoball** [comment]
> I’m still interested in switching to a kmz with icons embedded. But this seems like a good step forward in the mean time.

@matschaffer 

Created new issue; #758

**Pull request merged**
