### PR TITLE
Update rails to 4.2.11.1

### PR DESCRIPTION
**Pull request by eitoball**
SSIA

For https://github.com/Safecast/safecastapi/network/alert/Gemfile.lock/actionview/open

### CODE REVIEW

**Comment by eitoball** [comment]
> What does SSIA mean?

@auspicacious 

https://en.wiktionary.org/wiki/SSIA

**Comment by matschaffer** [comment]
TIL 😉

**Comment by auspicacious** [comment]
@eitoball please merge this to master when you have a moment.

**Comment by matschaffer** [comment]
Let's go for it ❤️

**Pull request merged**
