### PR TITLE
Device story

### PR DESCRIPTION
**Pull request by eitoball**

### CODE REVIEW

**Comment by matschaffer** [comment]
The engine thing is a little curious here. Just trying it out or does it provide some advantages?

**Comment by eitoball** [comment]
> The engine thing is a little curious here. Just trying it out or does it provide some advantages?

I guess that namespace and modulization are advantages.

**Comment by matschaffer** [comment]
Screen Shot 2019-12-26 at 9 13 35 PM

Any tips how how the tests on this are supposed to run?

**Comment by eitoball** [comment]
> Any tips how how the tests on this are supposed to run?

Please use #611 I am closing this PR.

**Pull request closed without merging**
