### PR TITLE
Stop exporting measurments in csv

### PR DESCRIPTION
**Pull request by robouden**
kaminari counting tweak

### CODE REVIEW

**Comment by matschaffer** [comment]
Interesting. Was there a slack conversation around this?

**Comment by nokton** [comment]
Why is this requested?

 Pieter

**Comment by eitoball** [comment]
No conversation nor request. I was going to propose to remove this feature. Mainly because csvbuilder gem has not been maintained and cannot be used in rails 4.

Maybe, we can look at access log to see if this feature is used or not.

**Comment by seanbonner** [comment]
I'd add that CSV is probably the most useful way we export the measurements and I'm constantly hearing from people about how glad they are we do it, so I don't think it's something we should stop at all.

**Comment by matschaffer** [comment]
FWIW, this doesn't impact the availability of https://api.safecast.org/system/measurements.tar.gz (the batch csv export)

The only match for `csv` in the logs is the test I just did, so doesn't seem like live CSV generation is really a used feature.

```
❯ ssh app1.safecast grep -i csv log/production.log
ActionView::MissingTemplate (Missing template bgeigie_imports/edit, application/edit with {:locale=>[:"en-US", :en], :formats=>[:html], :handlers=>[:erb, :builder, :jbuilder, :csvbuilder, :haml]}. Searched in:

~
❯ ssh app2.safecast grep -i csv log/production.log
[80c4a0068c252dc0e03c96cff89a2322] [162.243.100.197] Started GET "/measurements.csv" for 162.243.100.197 at 2016-06-10 00:40:06 +0000
[80c4a0068c252dc0e03c96cff89a2322] [162.243.100.197] Processing by MeasurementsController#index as CSV
[80c4a0068c252dc0e03c96cff89a2322] [162.243.100.197]   Rendered measurements/index.csv.csvbuilder (0.2ms)
[6b42d0b5fa750ffa2d792240171c5156] [162.243.100.197] Started GET "/measurements.csv" for 162.243.100.197 at 2016-06-10 00:40:11 +0000
[6b42d0b5fa750ffa2d792240171c5156] [162.243.100.197] Processing by MeasurementsController#index as CSV
[6b42d0b5fa750ffa2d792240171c5156] [162.243.100.197]   Rendered measurements/index.csv.csvbuilder (0.2ms)
```

**Comment by thinrope** [comment]
As discussed on Slack this just broke the graphs on realtime.safecast.org ...
I think having a CSV is very important, so alternative ways to generate it might be needed.

**Comment by matschaffer** [comment]
Should be online again momentarily now that #286 is merged

**Comment by nokton** [comment]
Yep - I also was wondering why this got deleted - lets revert back plz

**Comment by nokton** [comment]
We have far more pressing items in the backlog than these items - can we do some sorting of the items. Especially items requested by volunteers or projects should be on top of the list.

**Comment by matschaffer** [comment]
@nokton it's already reverted. https://waffle.io/Safecast/Safecastapi has the "ready" list that we tend to work basically top-to-bottom. 

What should be toward the top that isn't already?

**Comment by nokton** [comment]
Thanks!

**Pull request merged**
