### PR TITLE
Adjust table width

### PR DESCRIPTION
**Pull request by Nakushi64**
Added a button to toggle between layouts for the device story table.

### CODE REVIEW

**Comment by matschaffer** [comment]
Here's a screenshot for @robouden 

Screen Shot 2020-11-25 at 1 35 45

Seems a little weird to me, but if it helps I don't see a problem merging it.

Would be great to work on a responsive layout at some point after we get comments & attachments working for device stories.

**Comment by robouden** [comment]
Maybe make the width of the last seen filed double size, so we can post much more line at one. If possible even do not use the paging of the data.

**Review by robouden — COMMENTED** [review]
Seem ok!!

**Comment by robouden** [comment]
approved

**Review by matschaffer — APPROVED** [review]

**Pull request merged**
