### PR TITLE
Add czech and portuguese translations to locales

### PR DESCRIPTION
**Pull request by GuiHeurich**
*why*

There are translations in https://app.localeapp.com/projects/4489 which could be used. 

*what*

Add yaml files with translations in Czech and Portuguese to config/locales.

Rel: https://github.com/Safecast/safecastapi/issues/782

### CODE REVIEW

**Review by matschaffer — APPROVED** [review]
Looks great! how did you get the export?

**Comment by GuiHeurich** [comment]
There is a "downloads" tab somewhere on localeapp.

**Comment by matschaffer** [comment]
awesome! great find. I'll merge this for now. Do we need to update the UI to allow selection of the new locale as well?

**Comment by GuiHeurich** [comment]
I haven't tested that, actually, but will have a look.

**Comment by matschaffer** [comment]
Thanks! Hopefully it's easy and we can do it as part of https://github.com/Safecast/safecastapi/issues/782 - if not we can close that one and open another issue to add the locale selector for the UI.

**Pull request merged**
