### PR TITLE
Fix datetime format in JSON, not to include milliseconds

### PR DESCRIPTION
**Pull request by eitoball**
Rails 4 includes millisecond in datetime string of JSON format. This causes Drivecast iOS app an error described in Safecast/Drive-ios#4 .

### CODE REVIEW

**Comment by Frangible** [comment]
My opinion: we should consider keeping milliseconds.  The API is delivering an ISO/RFC complaint date.  Its behavior is correct.

iOS app: v1.1 is currently in testing and pending review by Apple.  It is passing all tests thus far.  It correctly handles dates from the API with or without the milliseconds, as per RFC/ISO standard.  (tested locally via http://api-staging.safecast.org vs. https://api.safecast.org)

However, we will need to support no-MS dates for a short period in the future until the app update is approved and users have a chance to download it.

**Comment by matschaffer** [comment]
@eitoball @Frangible how about we add a version number or a date to that comment so we know when it's (reasonably) safe to put the milliseconds back?

**Comment by Frangible** [comment]
v1.1 for the iOS app.  Date of Apple approval unknown.  7 days from this post seems likely safe.

**Comment by eitoball** [comment]
> how about we add a version number or a date to that comment so we know when it's (reasonably) safe to put the milliseconds back?

How about Android version? Any official clients?

**Comment by Frangible** [comment]
> How about Android version? Any official clients?  
  
Android app is "Safecast:Drive".  From what I saw on Slack, it appears unaffected.

**Comment by matschaffer** [comment]
Closing this now that the iOS app has been updated.

**Pull request closed without merging**
