### PR TITLE
Some ops docs regarding DB overload

### PR DESCRIPTION
**Pull request by matschaffer**

### CODE REVIEW

**Comment by robouden** [comment]
Seems good to me too.

**Comment by robouden** [comment]
Ant reason why CircleCI failed?

**Comment by matschaffer** [comment]
I'm still having some trouble getting circle to like our postgis setup

**Comment by matschaffer** [comment]
Not yet. The jobs will require some work before we can make use of a replica. The iOS export will probably need to stay on the primary since it makes some data modifications and uses temp tables which unfortunately postgres won't allow on replicas

**Pull request merged**
