### PR TITLE
Use PostgreSQL 9.5 on Travis CI

### PR DESCRIPTION
**Pull request by eitoball**

### CODE REVIEW

**Comment by matschaffer** [comment]
Any particular reasons here? Prod might still be running 9.2

**Comment by eitoball** [comment]
> Any particular reasons here? Prod might still be running 9.2

oh... I thought that api is using 9.5. Closing.

**Comment by matschaffer** [comment]
Yeah, 9.2

```
root@meerkat:~# ./psql
psql (9.3.22, server 9.2.5)
Type "help" for help.

safecast=#
```

**Comment by matschaffer** [comment]
Dev work on 9.5 is probably fine, but might want to keep travis closer to 9.2 incase of some odd incompatibility.

**Pull request closed without merging**
